myauth/urls.py
#from django.conf.urls import patterns, url
from django.conf.urls import url


from myauth import views


app_name = 'myauth'

urlpatterns = [
    #    url(r'^$', views.index, name='index'),
    url(r'^login/?$',views.login, name='login'),
    url(r'^demologin/?$',views.demologin, name='demologin'),
    url(r'^logout/?$',views.logout, name='logout'),
    url(r'^signup/?$',views.signup, name='signup'),
    url(r'^recover/?$',views.recover, name='recover'),
    url(r'^verify/?$',views.verify, name='verify'),
    url(r'^profile/?$',views.profile, name='profile'),
    url(r'^error/?$',views.error, name='error'),
#    url(r'^verify/(?P<email>[^\/]+)/(?P<code>[A-Z0-9a-z]+)?$',views.verify, name='verify'),
]

okerr/urls.py
#from django.conf.urls import patterns, include, url
#from django.conf.urls import include, url
from django.urls import path, re_path, include

#from emailusernames.forms import EmailAuthenticationForm
from django.contrib import admin
admin.autodiscover()
import okerrui.views

from django.conf import settings

#urlpatterns = patterns('',
#    # Examples:
#    url(r'^$',okerrui.views.index),
#    url(r'^okerr/',include('okerrui.urls',namespace='okerr')),
#    url(r'^auth/',include('myauth.urls',namespace='myauth')),
#    url(r'^admin/', include(admin.site.urls)),
#    url(r'^i18n/', include('django.conf.urls.i18n')),
#)



urlpatterns = [
    # Examples:
    re_path(r'^$', okerrui.views.index),
    #url(r'^okerr/',include('okerrui.urls' ,namespace='okerr')),
    re_path(r'', include('myauth.urls', namespace='myauth')),
    #url(r'^auth/',include('myauth.urls',namespace='myauth')),
    #re_path(r'^admin/', include(admin.site.urls)),
    path(r'admin/', admin.site.urls),
    re_path(r'^i18n/', include('django.conf.urls.i18n')),
    re_path(r'', include('okerrui.urls' ,namespace='okerr')),
    # url('', include('social_django.urls', namespace='social')),
    re_path(r'moveauth/', include('moveauth.urls' , namespace='moveauth')),
    re_path(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

okerrui/urls.py
#from django.conf.urls import patterns, url
from django.conf.urls import url
from django.views.generic import TemplateView

from okerrui import views, training


app_name = 'okerrui'

urlpatterns = [

    url('^oauth2/login/(?P<provider>[^/]+)(?P<suffix>.*)', views.oauth2_login, name='oauth2_login'),
    url('^oauth2/bind/(?P<provider>[^/]+)(?P<suffix>.*)', views.oauth2_bind, name='oauth2_bind'),
    url('^oauth2/callback', views.oauth2_callback, name='oauth2_callback'),
    url('^oauth2/select', views.oauth2_select, name='oauth2_select'),
    # url(r'oauth2/info/(<?P<provider>[^/]+)', views.oauth2_info, name='oauth2_info'),


    url(r'^sredir/(?P<name>[^/]+)/(?P<path>.*)', views.sredir, name='sredir'),

    url(r'afterlogin', views.afterlogin, name='afterlogin'),
    url(r'^$', views.index, name='index'),
    url(r'^sendsummary/(?P<textid>.+)', views.sendsummary, name='sendsummary'),
#    url(r'^setvpid/(?P<vpid>\d+)$', views.setvpid, name='setvpid'),
#    url(r'^setnovpid$', views.setvpid, name='setnovpid'),
    url(r'^$', views.index, name='index'),
#    url(r'^indicator/(?P<iid>\d+)$',views.indicator,name='indicator'),
    url(r'^indicator/(?P<iid>\d+)/ds$', views.indicator_ds, name='indicatords'),

    url(r'^i/(?P<pid>[^/]+)/(?P<iid>.+)$', views.ilocator, name='ilocator'),
    url(r'^i/(?P<iid>[^@]+)@(?P<pid>.+)$', views.ilocator, name='ilocatorat'),
    url(r'^i/(?P<textid>[^/]+)/?', views.pi, name='pi'),
#    url(r'^uptimelog/(?P<textid>[^/]+)/(?P<iname>.+)$',views.uptimelog,name='uptimelog'),

    url(r'^chproject', views.chproject, name='chproject'),

    url(r'^log/(?P<textid>[^/]+)$', views.project_log, name='project_log_nocode'),
    url(r'^log/(?P<textid>[^/]+)/(?P<codelist>.*)$', views.project_log, name='project_log'),


    url(r'^servers/(?P<pid>[^/]+)/?$',views.servers,name='servers'),

    # url(r'^servers/(?P<pid>[^/]+)/(?P<prepath>[^/]*)/(?P<path>[^/]+)',views.srvedit, name='srvedit'),
    url(r'^servers/(?P<pid>[^/]+)/(?P<prepath>[^/]*)/(?P<path>.+)', views.srvedit, name='srvedit'),

    url(r'^add/(?P<tid>.+)', views.add, name='add'),
    url(r'^doop/(?P<textid>.+)', views.doop, name='doop'),
    url(r'^invitations', views.invitations, name='invitations'),
    url(r'^acceptinvite', views.acceptinvite, name='acceptinvite'),
#    url(r'^policylist/?',views.policylist,name='policylist'),
    url(r'^policy/(?P<textid>[^/]+)/(?P<pname>.+)', views.policy, name='policy'),
    url(r'^projectlist/?', views.projectlist, name='projectlist'),
    url(r'^project/(?P<pid>.+)', views.project, name='project'),
    url(r'^pjson/(?P<pid>.+)', views.pjson, name='pjson'),
    url(r'^pdsjson/(?P<textid>[^/]+)/(?P<iname>.+)', views.pdsjson, name='pdsjson'),
    url(r'^rawpjson/(?P<tid>.+)', views.rawpjson, name='rawpjson'),
    url(r'^rawijson/(?P<iid>\d+)', views.rawijson, name='rawijson'),
    url(r'^keys/(?P<pid>[^/]+)/(?P<parentpath>.*)', views.keys, name='keys'),
    url(r'^keystext/(?P<pid>\d+)/(?P<parentpath>.*)', views.keystext, name='keystext'),
    url(r'^updatevkeys/(?P<pid>\d+)', views.updatevkeys, name='updatevkeys'),
    url(r'^resetkeys/(?P<pid>\d+)', views.resetkeys, name='resetkeys'),
    url('^toggle_interface_level/(?P<path>.+)', views.toggle_interface_level, name='toggle_interface_level'),

    #    url(r'^getkeytree/(?P<textid>[^\/]+)/(?P<path>.*)',views.getkeytree,name='getkeytree'),
    url(r'^exportkeyval/(?P<pid>[^\/]+)/(?P<path>.*)', views.exportkeyval, name='exportkeyval'),
    url(r'^exportkeyval_raw/(?P<pid>[^\/]+)/(?P<path>.*)', views.exportkeyval_raw, name='exportkeyval_raw'),

    url(r'^getnotifications', views.getnotifications, name='getnotifications'),
    url(r'^delnotification', views.delnotification, name='delnotification'),

#
#
    url(r'^wiznoflap/(?P<textid>[^/]+)/(?P<iname>.+)$', views.wiznoflap, name='wiznoflap'),
    url(r'^getsysvar/(?P<varname>.*)', views.getsysvar, name='getsysvar'),


    url(r'^getkeyval/(?P<textid>[^\/]+)/(?P<path>.*)', views.getkeyval, name='getkeyval'),
#    url(r'^getkeylist/(?P<textid>[^\/]+)/(?P<path>.*)',views.getkeylist,name='getkeylist'),
    url(r'^update/?', views.update, name='update'),
    url(r'^mirror/?', views.mirror, name='mirror'),
    url(r'^getpub/?', views.getpub, name='getpub'),
    url(r'^eula', views.eula, name='eula'),
    url(r'^motd', views.motd, name='motd'),
    url('^firstlogin', views.firstlogin, name='firstlogin'),
    url(r'^afterlife', views.afterlife, name='afterlife'),
    url(r'^bonusverify', views.bonusverify, name='bonusverify'),
    url(r'^tview', TemplateView.as_view(template_name='okerrui/eula.html')),
    url(r'^cat', views.cat, name='cat'),



    #
    # # # MODULES # # #
    #

    # STATUSPAGE
    url(r'^status/(?P<textid>[^/]+)/(?P<addr>.*)', views.status, name='status'),
    url(r'^jstatus/(?P<textid>[^/]+)/(?P<addr>.*)', views.jstatus, name='jstatus'),
    url(r'^statuspage/(?P<textid>[^/]+)/(?P<addr>.*)', views.statuspage, name='statuspage'),
    url(r'^statussubscribe/(?P<textid>[^/]+)/(?P<addr>[^/]+)/(?P<date>[^/]+)/(?P<email>[^/]+)/(?P<code>.+)',
        views.statussubscribe, name='statussubscribe'),
    url(r'^statusunsubscribe/(?P<textid>[^/]+)/(?P<addr>[^/]+)/(?P<date>[^/]+)/(?P<email>[^/]+)/(?P<code>.+)',
        views.statusunsubscribe, name='statusunsubscribe'),



    # TRAINING
    url(r'training/(?P<code>.*)', training.training, name='trainingcode'),
    url(r'training', training.training, name='training'),

    # DYNDNS
    url(r'dyndns/(?P<textid>[^/]+)/(?P<name>.*)', views.dyndns, name='dyndns'),


#    url(r'^project_backup/(?P<pid>\d+)?', views.project_backup, name='project_backup'),
#    url(r'^email_backup/(?P<pid>\d+)?', views.email_backup, name='email_backup'),





    ### API ###

    url(r'^api/indicators/(?P<pid>[^/]+)/?$', views.api_indicators, name='api_indicators'),
    url(r'^api/indicators/(?P<pid>[^/]+)/(?P<prefix>.+)', views.api_prefix, name='api_prefix'),
#    url(r'^api/getiname/(?P<pid>.+)/(?P<idname>.*)', views.api_getiname, name='api_getiname'),
#    url(r'^api/getiid/(?P<pid>.+)/(?P<idname>.*)', views.api_getiid, name='api_getiid'),
    url(r'^api/filter/(?P<pid>[^/]+)/(?P<kvlist>.*)', views.api_filter, name='api_filter'),
    url(r'^api/tagfilter/(?P<pid>[^/]+)/(?P<tagline>.*)?', views.api_tagfilter, name='api_tagfilter'),
    url(r'^api/indicator/(?P<pid>[^/]+)/(?P<iid>.+)', views.api_indicator, name='api_indicator'),
    url(r'^api/set/(?P<pid>[^/]+)/(?P<iid>.+)', views.api_set, name='api_set'),
    url(r'^api/get/(?P<pid>[^/]+)/(?P<iid>.+)/(?P<argname>.+)', views.api_get, name='api_getarg'),
    url(r'^api/create/(?P<pid>[^/]+)/(?P<iname>.+)', views.api_create, name='api_create'),
    url(r'^api/delete/(?P<pid>[^/]+)/(?P<iname>.+)', views.api_delete, name='api_delete'),
    url(r'^api/checkmethods', views.api_checkmethods, name='api_checkmethods'),
    url(r'^api/recheck/(?P<pid>[^/]+)/?$', views.api_recheck, name='api_recheck'),

    url(r'^api/director/(?P<textid>.*)', views.api_director, name='api_director'),
    url(r'^api/check_version/(?P<product>[^/]+)/(?P<version>.+)', views.api_check_version, name='api_check_version'),

    # compatibility aliases
    url(r'^api/getarg/(?P<pid>[^/]+)/(?P<iid>.+)/(?P<argname>.+)', views.api_get, name='api_get'),
    url(r'^api/setarg/(?P<pid>[^/]+)/(?P<iid>.+)', views.api_set, name='api_set'),

    ### Partner API ####
    url(r'^api/partner/check/(?P<partner_id>.+)', views.api_partner_check, name='api_partner_check'),
    url(r'^api/partner/list', views.api_partner_list, name='api_partner_list'),
    url(r'^api/partner/create', views.api_partner_create, name='api_partner_create'),
    url(r'^api/partner/grant', views.api_partner_grant, name='api_partner_grant'),
    url(r'^api/partner/revoke', views.api_partner_revoke, name='api_partner_revoke'),

#    url(r'^api/partner/preconfigure', views.api_partner_preconfigure, name='api_partner_preconfigure'),


    ### Private API ###
#    url(r'^api/sync/?(?P<tstamp>\d+)?', views.api_sync, name='api_sync'),
#    url(r'^api/fsync/?(?P<opts>.*)', views.api_fsync, name='api_fsync'),
    url(r'^api/plist', views.api_plist, name='api_plist'),
    url(r'^api/profile/(?P<pid>.+)', views.api_profile, name='api_profile'),
    url(r'^api/myprofile', views.api_myprofile, name='api_myprofile'),

    # url(r'^api/project/(?P<tid>.+)', views.api_project, name='api_project'),
#    url(r'^api/sdump/?(?P<srid>.+)?', views.api_sdump, name='api_sdump'),
    url(r'^api/tproc/get', views.api_tproc_get, name='api_tproc_get'),
    url(r'^api/tproc/set', views.api_tproc_set, name='api_tproc_set'),
    url(r'^api/listcluster', views.api_listcluster, name='api_listcluster'),
    url(r'^api/hostinfo', views.api_hostinfo, name='api_hostinfo'),
    url('^api/ip', views.api_ip, name='api_ip'),
    url(r'^api/status', views.api_status, name='api_status'),
#    url(r'^api/summary', views.api_summary, name='api_summary'),
    url(r'^api/setci$', views.api_setci, name='api_setci'),
    url(r'^api/groups', views.api_groups, name='api_groups'),
    url(r'^api/test', views.api_test, name='api_test'),


    url(r'^api/admin/list$', views.api_admin_list, name='api_admin_list'),
    url(r'^api/admin/cilist$', views.api_admin_cilist, name='api_admin_cilist'),
    url(r'^api/admin/export/(?P<email>.*)', views.api_admin_export, name='api_admin_export'),
    url(r'^api/admin/member/(?P<email>.*)', views.api_admin_member, name='api_admin_member'),
    url(r'^api/admin/accept_invite', views.api_admin_accept_invite, name='api_admin_accept_invite'),

    url(r'^api/admin/tglink', views.api_admin_tglink, name='api_admin_tglink'),
    url(r'^api/admin/qsum/(?P<textid>.*)', views.api_admin_qsum, name='api_admin_qsum'),
    url(r'^api/admin/chat_id/(?P<chat_id>.*)', views.api_admin_chat_id, name='api_admin_chat_id'),

    url(r'^api/admin/force_sync', views.api_admin_force_sync, name='api_admin_force_sync'),
    url(r'^api/admin/log/?(?P<mname>[^/]*)/?(?P<start>.*)', views.api_admin_log, name='api_admin_log'),

]

myauth/models.py
from django.db import models
from django.utils import timezone
import datetime
import string
import random

# Create your models here.
class SignupRequest(models.Model):
    email = models.CharField(max_length=200) 
    created = models.DateTimeField(default=timezone.now, blank=True)
    code = models.CharField(max_length=200)

    def gencode(self):
        self.code = ''.join(random.choice(string.ascii_uppercase + string.digits) for _ in range(10))

    def __str__(self):
        return self.email

    @staticmethod
    def cron():
        # delete old signup requests
        time = timezone.now() - datetime.timedelta(days=1)
        SignupRequest.objects.filter(created__lt=time).delete()
        

templates/myauth/afterrecover.html
{% extends "okerrui/base.html" %}
{% load i18n %}

{% block content %}

    
    {% if error_message %}
        <strong>{{ error_message }}</strong>
    {% endif %}

    <h1>Password recovery</h1>
    Email is sent to your email address {{ email }} with verification code. Please check your mailbox and enter code at <a href="{% url 'myauth:verify' %}">verification page</a>.

{% endblock %}

templates/myauth/aftersignup.html
{% extends "okerrui/base.html" %}
{% load i18n %}

{% block content %}

    
    {% if error_message %}
        <strong>{{ error_message }}</strong>
    {% endif %}

    <h1>Thanks for signup!</h1>
    Email is sent to your email address {{ email }} with verification code. Please check your mailbox and enter code at <a href="{% url 'myauth:verify' %}">verification page</a>.

{% endblock%}

templates/myauth/empty.html
{% extends "okerrui/base.html" %}
{% block content %}
    
{% endblock %}

templates/myauth/login.html
{% extends "okerrui/base.html" %}
{% load i18n %}
{% load markup_tags %}

{% block content %}

    {% if prelogin %}
    <div style="text-align: center;">
        <div class="motd">{{prelogin|apply_markup:"markdown"}}</div>
    </div>
    {% endif %}

    <div style="text-align: center;">

        <div class="loginpass">
            <form action="{% url 'myauth:login' %}" method="post">
            {% csrf_token %}
            <table border=0 align=center>
            <tr>
            <td>{% trans 'Email' %}:</td>
            <td><input type=text name="username"></td>
            </tr>
            <tr>
            <td>{% trans 'Password' %}:</td>
            <td><input type=password name="password"></td>
            </tr>
            <tr>
            <td align=center>
                <button class='massButton' name='login' value='1'>{% trans 'Login' %}</button>
            </td>
            <td align=right>
                <a href="{% url 'myauth:demologin' %}">{% trans 'Demo' %}</a>
            </td>
            </tr>
            <tr>
            <td align=left><a href="{% url 'myauth:signup' %}">{% trans 'Register' %}</a></td>
            <td align=right><a href="{% url 'myauth:recover' %}">{% trans 'Forgot password' %}</a></td>
            </tr>
            </table>
            </form>

        </div>


        {% if oauth2_providers %}
        <div class="oauth-block">
            {% trans 'Login or register via oauth2' %}:<br>
            {% for pcode, ps in providers.items %}
                <div class="oauth-button">
                    <a href="{% url "okerr:oauth2_login" pcode next %}">
                        <img src="{{ps.logo}}" alt="{{ps.title}}"><br>
                        {{ps.title}}
                    </a>
                </div>
            {% endfor %}
            <p>
            {% for p in oauth2_providers %}
                <div class="oauth-button">
                    <a href="{% url "okerr:oauth2_login" p.code next%}">
                        <img src="{{p.logo}}" alt="{{p.title}}"><br>
                        {{p.title}}
                    </a>
                </div>
            {% endfor %}
            </p>
        </div>
        {% endif %}

    </div>   

{% endblock %}

templates/myauth/profile.html
{% extends "okerrui/base.html" %}
{% load i18n %}
{% load static %}

{% block content %}

    <form action="{% url 'myauth:profile' %}" method="post">
    {% csrf_token %}
    <table border=0>

    <tr>
    <td>{% trans 'Username' %}:</td>
    <td>{{ user.username }}</td>
    </tr>


    <tr>
    <td>{% trans 'First Name' %}:</td>
    <td><input type=text name="first_name" value={{ user.first_name }}></td>
    </tr>


    <tr>
    <td>{% trans 'Last Name' %}:</td>
    <td><input type=text name="last_name" value={{ user.last_name }}></td>
    </tr>


    <tr>
    <td>{% trans 'Telegram username' %}:</td>
    <td><input type=text name="telegram_name" value={{ profile.telegram_name }}>
        {% if profile.telegram_chat_id %}
            ({% trans 'Linked' %})
        {% else %}
            ({% trans 'Not linked' %})
        {% endif %}
    </td>
    </tr>

    <tr>
    <td>{% trans 'Created' %}</td>
    <td>{{ user.date_joined }}</td>
    </tr>

    <tr>
    <td>{% trans 'Training' %}</td>
    <td>
        {% if profile.training_stage == 'basic:DONE' %}
            {% trans 'Completed' %}
        {% elif profile.training_stage %}
            <a href="{% url 'okerr:training' %}">{% trans 'Continue' %}</a>
        {% else %}
            <a href="{% url 'okerr:training' %}">{% trans 'Begin' %}</a>
        {% endif%}
    
    </td>
    </tr>


   <tr class='title'><td></td><td>{% trans 'Access' %}</td></tr>


    <tr>
    <td>{% trans 'Group(s)' %}:</td>
    <td>
        {% for g in groups %}
            [ {{g.name}}
        {% if g.expires %}
            <span class="dull">({{g.left}})</span>
        {% endif %}
        ]
        {% endfor %}
    </td>
    </tr>

    <tr>
    <td>{% trans 'Perk(s)' %}:</td>
    <td>
        {% for g in perks %}
            [ {{g.name}}
        {% if g.expires %}
            <span class="dull">({{g.left}})</span>
        {% endif %}
        ]
        {% endfor %}
    </td>
    </tr>


    <tr>
        <td>{% trans 'Parameters' %}:</td>
    </tr>
    {% for name,val in args.items %}
    <tr>
        <td>&nbsp;.&nbsp;.&nbsp;{{name}}</td>
        <td>{{val}}</td>
    </tr>
    {% endfor %}

    {% if qi %}
    <tr>
        <td>{% trans 'Quick indicators' %}:</td>
    </tr>
        {% for period, num in qi.items%}
    <tr>
        <td>&nbsp;{% trans 'Period' %}: {{period}}s</td>
        <td>{% trans 'Indicators' %}: {{num}}</td>
    </tr>
            
        {% endfor %}
    {% endif %}
    <tr>
    <td>{% trans 'Projects' %}:</td>
    <td>
        {% for t in profile.projects %}
            <a href="{% url 'okerr:pi' t.get_textid %}">{{t.name}}</a>
            <a href="{% url 'okerr:project' t.id %}"><img src="{% static 'wrench.png' %}"></a>
        {% endfor %}
    </tr>



        {% if oauth2_bound or oauth2_notbound %}

    <tr class='title'><td></td><td>{% trans 'OAuth authentication' %}</td></tr>

    <tr>
    <td>
        <ul>

        {% for p in oauth2_bound %}
                <li>{{p.title}} ({% trans 'Bound' %})</li>
        {% endfor %}

        {% for p in oauth2_notbound %}
                <li>{{p.title}} <a href="{% url "okerr:oauth2_bind" p.code '/profile' %}">
                    {% trans 'Bind' %}
                    </a></li>
        {% endfor %}

        </ul>

    </td>
    </tr>
        {% if oauth2_bound%}
    <tr>
    <td><input type=checkbox name="oauth_clean"> {% trans 'Clean all OAuth binding' %}</td>
    </tr>
        {% endif %}



        {% endif %}




    <tr class='title'><td></td><td>{% trans 'Outgoing emails' %}</td></tr>

    <tr>
    <td>{% trans 'Send summaries' %}</td>
    {% if profile.sendsummary %}
    <td><input type=checkbox name="sendsummary" checked></td>
    {% else %}
    <td><input type=checkbox name="sendsummary"></td>
    {% endif %}
    </tr>

    <tr>
    <td>{% trans 'Daily summary time' %} (UTC)</td>
    <td><input type=text name="sumtime" size=6 value="{{profile.sumtimehhmm}}"></td>
    </tr>

    <tr>
    <td>{% trans 'Next summary time' %} (UTC)</td>
    <td>{{profile.nextsummary}}</td>
    </tr>

    <tr>
    <td>{% trans 'Send alerts' %}</td>
    {% if profile.sendalert %}
    <td><input type=checkbox name="sendalert" checked></td>
    {% else %}
    <td><input type=checkbox name="sendalert"></td>
    {% endif %}
    </tr>


    <tr class='title'><td></td><td>{% trans 'Bonus code' %}</td></tr>

    <tr>
    <td>{% trans 'Bonus code' %}</td>
    <td><input type=text name="bonus_code" autocomplete="off" value=""></td>
    </tr>

    <tr class='title'><td></td><td>{% trans 'Password' %}</td></tr>

    <tr>
    <td>{% trans 'Current password' %} ({% trans 'required' %}):</td>
    <td><input type=password name="password"></td>
    </tr>
 
    <tr>
    <td>{% trans 'New password' %}:</td>
    <td><input type=password name="pass1" value=""></td>
    </tr>

    <tr>
    <td>{% trans 'New password'%} ({% trans 'verification' %}):</td>
    <td><input type=password name="pass2" value=""></td>
    </tr>
 
 
    <tr class='title'><td></td><td>{% trans 'Delete account' %}</td></tr>

    <tr>
    <td colspan=2><input type=checkbox name="suicide">{% trans 'Delete account (irreversibly)' %}</td>
    </tr>
 
    <tr>
    <td>{% trans "'Yes, I am sure!'" %}</td>
    <td><input type=text name=iamsure></td>
    </tr>



    </table>
    <button class='massButton' name='change' value='1'>{% trans 'Change' %}</button>
    </form>

</html>

{% endblock %}

templates/myauth/recover.html
{% extends "okerrui/base.html" %}
{% load i18n %}

{% block content %}


    <form action="{% url 'myauth:recover' %}" method="post">
    {% csrf_token %}
    <table align=center>
    <tr>
        <td>{% trans 'Email' %}:</td>
        <td><input type=text name="email"></td>
    </tr>
    <tr>
        <td colspan=2 align=center>
            <input type=submit name=login value="{% trans 'Recover' %}">   
        </td>
    </tr>
    </table>
    
    </form>

{% endblock %}

templates/myauth/registered.html
{% extends "okerrui/base.html" %}
{% load i18n %}

{% block content %}

    
    {% if error_message %}
        <strong>{{ error_message }}</strong>
    {% endif %}

    <h1>Registered!</h1>
    Congratulations, you are registered!
    <p>
    username: {{ username }}
    password: {{ password }}
    <p>
    <a href="{% url 'myauth:login' %}">Log in</a> and please change password immediately.

{% endblock %}

templates/myauth/signup.html
{% extends "okerrui/base.html" %}
{% load i18n %}
{% block content %}

    
    <form action="{% url 'myauth:signup' %}" method="post">
    {% csrf_token %}

    <table align=center>
    <tr><td colspan=2>
    {% with "eula."|add:lang_code|add:".txt" as loceula %}
    <textarea readonly rows=20 cols=80>{% include loceula %}</textarea>
    {% endwith %}
    </td></tr>
    <tr><td colspan=2>
        <input type=checkbox name=iaccept>{% trans 'I accept End-User License Agreement'%}
    </td></tr>


    <tr>
        <td>Email:</td>
        <td><input type=text name="email" value={{email}}></td>
    </tr>
    <tr>
        <td colspan=2 align=center>
            <input type=submit name=login value="{% trans 'Signup' %}">   
        </td>
    </tr>
    </table>
    
    </form>

{% endblock %}

templates/myauth/verify.html
{% extends "okerrui/base.html" %}
{% block content %}
    
    <form action="{% url 'myauth:verify' %}" method="get">
    {% csrf_token %}
    <table align=center>
    <tr>
    <td>Email:</td>
    <td><input type=text name="email"></td>
    </tr>
    <tr>
    <td>Verification Code:</td>
    <td><input type=text name="code"></td>
    </tr>
    <tr>
        <td colspan=2 align=center>
            <input type=submit name=login value="Verify">
        </td>
    </tr>
    </table>
    </form>
{% endblock %}